export const womanData =[
    {
        name: "Patsy Mink",
        description:" Patsy Mink was the first Asian American woman who was elected to the house of representatives in 1964. After having faced both racism and sexism growing up, she worked hard to fight segregation policies. She even became the first person ever to oppose a Supreme Court nominee on the basis of discrimination against women. She served a total of 12 terms ( so 24 years!), split between representing Hawaii'sat large congressional district and the second congressional district.",
        category:"politics",
        top:"300px",
        left:"450px",
        img_alt:"Patsy_Mink",
        img_src:"playground_assets/Patsy_Mink_1970s.jpg",
        img_classname:"homepage-image-woman",
        icon_alt:"House of Representatives",
        icon_src:"playground_assets/United_States_House_of_Representatives_chamber.jpg",
        icon_classname:"homepage-image-icon-woman",
        icon_width:"150px",
        icon_height:"150px",
        icon_top:"-26px",
        link:"https://en.wikipedia.org/wiki/Patsy_Mink",
        link_classname:"homepage-link-woman",
      
        lifespan:"1927-2002",
    
    },{
        name:"Hedy Lamarr",
        category:"science",
        description:"Hedy Lamarr was an Austrian-born actress and inventor. During world war II she was involved in the invention of system for frequency hopping to prevent spionage from the germans. This invention later became the basis of many of our modern wireless communications like GPS, Bluetooth and of course Wi-Fi.",
        lifespan:"1914-2000",
        link:"https://en.wikipedia.org/wiki/Hedy_Lamarr",
        img_src:"/playground_assets/hedy-lamarr-g61dc56ee2_1920.jpg",
        img_alt:"Hedy Lamarr in The Heavenly Body 1944",
        icon_src:"/playground_assets/kisspng-gps-navigation-systems-global-positioning-system-g-checkpoint-5b111df1414f17.5064716415278484332675-200h.png",
        icon_alt:"GPS invented by Hedy Lamarr logo",
    },{
        name:"Gladys Bentley",
        category:"human",
        description:" After running away at 16 to New York her characteristically deep voice quickly helped her to fame during the Halrem renaissance days as a talented blues singer and cross dresser.",
        lifespan:"1907-1960",
        link:"https://de.wikipedia.org/wiki/Gladys_Bentley",
        img_src:"playground_assets/Gladys_Bentley.jpg",
        img_alt:" Glady Bentley blues singer and cross dresser in a white suit",
        icon_src:"playground_assets/LGBT_Rainbow_Flag.png",
        icon_alt:"LGBTQ+ LGBTQ rights flag ",
    },
    {
        name:"Henrietta Lacks",
        category:"medicine",
        description:"After dying from cervical cancer in 1951, cancer cells were taken from Henrietta's body to study (without her prior consent!). These cells were then used to form the first immortalized human cell line known as the HeLa line, which are used to this day in medical research. They became central for cancer research and were even used to test the polio vaccine on, making it available a lot sooner thant otherwise would have been possible.",
        lifespan:"1920-1951",
        link:"https://en.wikipedia.org/wiki/Henrietta_Lacks",
        img_src:"playground_assets/Henrietta_Lacks_statue_at_Royal_Fort_House%2C_Bristol.jpg",
        img_credit: "14GTR, CC BY-SA 4.0 <https://creativecommons.org/licenses/by-sa/4.0>, via Wikimedia Commons",
        img_alt:"Henrietta Lacks HeLa cell line donator portrait",
        icon_src:"/playground_assets/580b585b2edbce24c47b2921.png",
        icon_alt:"Polio vaccine syringe",
    },
    {
        name:"Faith Spotted Eagle",
        category:"human",
        lifespan:"1948-",
        description:"As a member of the Yanktion Sioux Nation and american activist Faith Spotted Eagele is a key figure in the fight for the rights of the group. She fought against was involved in the attempt to block the development of the dacota access pipe. Furthermore she is a founding member of the brave heart society, that teaches young girls about traditional culture and in 2016 even received a single electoral vote for the Presidency of the US.",
        link:"https://en.wikipedia.org/wiki/Faith_Spotted_Eagle",
        img_src:"playground_assets/Faith_Spotted_Eagle.png",
        img_alt:"Faith spotted eagle american human rights activist portrait",
        img_credit: "Four Worlds Europe, CC BY 3.0 <https://creativecommons.org/licenses/by/3.0>, via Wikimedia Commons",
        icon_src:"playground_assets/American_House_protest.png",
        icon_credit: "Desiree Kane, CC BY 3.0 <https://creativecommons.org/licenses/by/3.0>, via Wikimedia Commons",
        icon_alt:"Eagel representing american human rights activist faith spotted eagle",
    },
    {
        name:"Eunice Foote",
        category:"science",
        description:"Despite its relevance, only few people know of Eunice Foote, the american scientist who in 1850 3 years before the better known british scientist John Tyndall, publshied the results of her experiments regarding an effect that later became known as the greenhouse effect. In her experminets she showed the ability of atmospheric water vapor and CO2 to affect solar heating.",
        lifespan:"1819-1888",
        link:"https://en.wikipedia.org/wiki/Eunice_Newton_Foote",
        img_src:"/playground_assets/eunice_newton_foote-1500h.png",
        img_alt:"Eunice Foote woman inventor and scientist portrait",
        icon_src:"/playground_assets/CO2.png",
        icon_credit: "Co2 Icons erstellt von Good Ware -Flaticon",
        icon_alt:"Carbon dioxide molecule structure",
    },
    {
        name:"Lise Meitner",
        category:"science",
        description:"It was Lise Meitner who suggested firing neutrons at uranium atoms, leading to the discovery of Nuclear fission. As a jewish woman in Germany during the Nazi-reign however she never got recognition for her contribution when she had to flee to Sweden, where she continued her work. She did not share the 1944 nobel prize in chemistry that was awarded to Otto Hahn for the discovery and only got formal recognition later in life for example in 1966 being accreditted the Enrico Fermi Award, 30 years after her initial discovery.",
        lifespan:"1878-1968",
        link:"https://en.wikipedia.org/wiki/Lise_Meitner",
        img_src:"/playground_assets/lise_meitner_%5B1878-1968%5D%2C_lecturing_at_catholic_university%2C_washington%2C_d.c.%2C_1946-200w.jpg",
        img_alt:"Lise Meitner woman scientist in her labaratory portrait",
        icon_src:"/playground_assets/nuclear_fission-200h.png",
        icon_alt:" Nuclear fission explanatory model discovered by Lise Meitner",
        icon_credit: "Original:  Stefan-Xp (talk · contribs) / Vectorization:  Wondigoma (talk · contribs), CC BY-SA 3.0 <http://creativecommons.org/licenses/by-sa/3.0/>, via Wikimedia Commons",
    },
    {
        name:"Paulina Luisi",
        category:"politics",
        description:"Paulina Luisi is the first latin american woman to participate in teh League of Nations as a government representative. She is also the first Uruguayan woman to ever receive a medical degree. As part of the feminist movement she fought for women's right to vote and obligatory sex-health education in schools.",
        lifespan:"1875-1950",
        link:"https://en.wikipedia.org/wiki/Paulina_Luisi",
        img_src:"playground_assets/Paulina_Luisi.jpg",
        img_alt:"Paulina Luisi",
        icon_src:"playground_assets/Flag_of_the_League_of_Nations.svg",
        icon_alt:" Woman education league of nations ",
        icon_credit: "Martin Grandjean This W3C-unspecified vector image was created with Inkscape., CC BY-SA 4.0 <https://creativecommons.org/licenses/by-sa/4.0>, via Wikimedia Commons",
    },
    {
        name:"Grace Hopper",
        category:"science",
        description:"If you are using computers or are reading this on a computer right now, then you should know Grace Hopper. She started working with computers very early on, when they were still filling up whole rooms. It used to be very hard to give computers instructions because they only understand computer code. But Grace thought it should be possible to make the communication between human and computer easier. So she invented the first computer compiler:  A program that translates instructions written by humans into code that the computer understands. Her biggest joy though came from teaching others about computers, which she did until her death in 1992.",
        lifespan:"",
        link:"https://en.wikipedia.org/wiki/Grace_Hopper",
        img_src:"playground_assets/Grace_Hopper.jpg",
        img_alt:"Grace Hopper as an old woman",
        icon_src:"playground_assets/my-computer--v1.png",
        icon_alt:"A computer icon symbolizing Grace Hoppers invention of the compiler",
    },
    {
        name:"Frances Ellen Watkins Harper",
        category:"human",
        description:"A poet, a teacher an sufragette, Ellen Watkins Harper was one of the most well-known black writers of her time. A time when much of America was still in the grips of slavery. Born to free parents she spoke out agains slavery and discrimination of all kinds and fought bravely for racial justice and gender equality. She joined the American Anti-Slavery Society and as a consequence became even more active as an activist and public cpeaker",
        lifespan:"1825-1911",
        link:"https://de.wikipedia.org/wiki/Frances_Harper",
        img_src:"/playground_assets/Frances_Ellen_Watkins_Harper.jpg",
        img_alt:"Frances Ellen Watkins Harper as a young woman",
        icon_src:"/playground_assets/poetry_by_frances_harper.png",
        icon_alt:"Poetry Icon",
        icon_credit:"Poetry icons created by Freepik - Flaticon</a>",
        icon_credit_link:"https://www.flaticon.com/free-icons/poetry",
    }
    
]