export const womanData =[
    {
        name:"Anna-Lena",
          description:"After dying from cervical cancer in 1951, cancer cells were taken from here body without her prior consent. These cells were studies and used extensively in medical research since they were used to form the first immortalized human cell line known as the HeLa line. These cells were also later used to test the polio vaccine on, making it available a lot sooner thant otherwise would have been possible.",
          category:"medicine",
          top:"500px",
          left:"400px",
          img_alt:"Anna-Lena",
          img_src:"https://upload.wikimedia.org/wikipedia/en/d/d7/Henrietta_Lacks_%281920-1951%29.jpg",
          img_classname:"homepage-image-woman",
          icon_alt:"Polio_vaccine",
          
          icon_src:"/playground_assets/syringe-200h.png",
          icon_classname:"homepage-image-icon-woman",
          link:"https://en.wikipedia.org/wiki/Henrietta_Lacks",
          link_classname:"homepage-link-woman",
          lifespan:"2003-?"
          
    },
    {
        name: "Patsy Mink",
        description:" She was the first asian -american woman who was elected to the house of representatives in 1964. Having faced racism and sexism growing up, she worked hard to fight segregation policies and later became the first one to oppose a Supreme Court nominee on the basis of discrimination against women. She served a total of 12 terms (24 years), split between representing Hawaii'sat-large congressional district and the second congressional district.",
        category:"politics",
        top:"300px",
        left:"450px",
        img_alt:"Patsy_Mink",
        img_src:"https://upload.wikimedia.org/wikipedia/commons/c/ce/Patsy_Mink_1970s.jpg",
        img_classname:"homepage-image-woman",
        icon_alt:"House of Representatives",
        icon_src:"https://upload.wikimedia.org/wikipedia/commons/9/90/United_States_House_of_Representatives_chamber.jpg",
        icon_classname:"homepage-image-icon-woman",
        icon_width:"150px",
        icon_height:"150px",
        icon_top:"-26px",
        link:"https://en.wikipedia.org/wiki/Patsy_Mink",
        link_classname:"homepage-link-woman",
      
        lifespan:"1927-2002",
    
    },{
        name:"Hedy Lamarr",
        category:"science",
        description:"Hedy Lamarr was an Austrian-born actress and inventor. During world war II she helped invent a system for frequency hopping to prevent spionage from the germans. This invention was a lso the basis for later development of other wireless communication like Wi-Fi, GPS or Bluetooth.",
        lifespan:"1914-2000",
        link:"https://en.wikipedia.org/wiki/Hedy_Lamarr",
        img_src:"/playground_assets/hedy-lamarr-g61dc56ee2_1920.jpg",
        img_alt:"Hedy Lamarr in The Heavenly Body 1944",
        icon_src:"/playground_assets/kisspng-gps-navigation-systems-global-positioning-system-g-checkpoint-5b111df1414f17.5064716415278484332675-200h.png",
        icon_alt:"GPS invented by Hedy Lamarr logo",
    },{
        name:"Gladys Bentley",
        category:"human",
        description:"Gladys Bentley was an Renaissance blues singer and cross dresser. After running away at 16 to New York her characteristically deep voice quickly helped her to fame during the Halrem renaissance.",
        lifespan:"1907-1960",
        link:"https://de.wikipedia.org/wiki/Gladys_Bentley",
        img_src:"https://upload.wikimedia.org/wikipedia/commons/b/b5/Gladys_Bentley_2.jpg",
        img_alt:" Glady Bentley blues singer and cross dresser in a white suit",
        icon_src:"https://upload.wikimedia.org/wikipedia/commons/8/8a/LGBT_Rainbow_Flag.png",
        icon_alt:"LGBTQ+ LGBTQ rights flag ",
    },
    {
        name:"Henrietta Lacks",
        category:"medicine",
        description:"After dying from cervical cancer in 1951, cancer cells were taken from here body without her prior consent. These cells were studies and used extensively in medical research since they were used to form the first immortalized human cell line known as the HeLa line. These cells were also later used to test the polio vaccine on, making it available a lot sooner thant otherwise would have been possible.",
        lifespan:"1920-1951",
        link:"https://en.wikipedia.org/wiki/Henrietta_Lacks",
        img_src:"https://upload.wikimedia.org/wikipedia/commons/9/9e/Henrietta_Lacks_statue_at_Royal_Fort_House%2C_Bristol.jpg",
        img_credit: "14GTR, CC BY-SA 4.0 <https://creativecommons.org/licenses/by-sa/4.0>, via Wikimedia Commons",
        img_alt:"Henrietta Lacks HeLa cell line donator portrait",
        icon_src:"/playground_assets/580b585b2edbce24c47b2921.png",
        icon_alt:"Polio vaccine syringe",
    },
    {
        name:"Faith Spotted Eagle",
        category:"human",
        lifespan:"1948-",
        description:"As a member of the Yanktion Sioux Nation and american activist Faith Spotted Eagele was involved in the attempt to blick the development of the dacota access pipe. Furthermore she is a founding member of the brave heart society, that teaches young girls about traditional culture and in 2016 even received a single electoral vote for the Presidency of the US.",
        link:"https://en.wikipedia.org/wiki/Faith_Spotted_Eagle",
        img_src:"https://upload.wikimedia.org/wikipedia/commons/8/83/Faith_Spotted_Eagle_%28cropped%29.png",
        img_alt:"Faith spotted eagle american human rights activist portrait",
        img_credit: "Four Worlds Europe, CC BY 3.0 <https://creativecommons.org/licenses/by/3.0>, via Wikimedia Commons",
        icon_src:"https://upload.wikimedia.org/wikipedia/commons/2/2a/%22Happi%22_American_Horse_direct_action_against_DAPL%2C_August_2016_%28cropped%29.png",
        icon_credit: "Desiree Kane, CC BY 3.0 <https://creativecommons.org/licenses/by/3.0>, via Wikimedia Commons",
        icon_alt:"Eagel representing american human rights activist faith spotted eagle",
    },
    {
        name:"Eunice Foote",
        category:"science",
        description:"Despite its relevance, only few people know of Eunice Foote, the american scientist who in 1850 3 years before the better known british scientist John Tyndall, publshied the results of her experiments regarding an effect that later became known as the greenhouse effect. In her experminets she showed the ability of atmospheric water vapor and CO2 to affect solar heating.",
        lifespan:"1819-1888",
        link:"https://en.wikipedia.org/wiki/Eunice_Newton_Foote",
        img_src:"/playground_assets/eunice_newton_foote-1500h.png",
        img_alt:"Eunice Foote woman inventor and scientist portrait",
        icon_src:"https://www.flaticon.com/de/kostenlose-icons/co2",
        icon_credit: "Co2 Icons erstellt von Good Ware -Flaticon",
        icon_alt:"Carbon dioxide molecule structure",
    },
    {
        name:"Lise Meitner",
        category:"science",
        description:"It was Lise Meitner who suggested firing neutrons at uranium atoms, leading to the discovery of Nuclear fission. As a jewish woman in Germany during the Nazi-reign however she never got recognition for her contribution when she had to flee to Sweden, where she continued her work. She did not share the 1944 nobel prize in chemistry that was awarded to Otto Hahn for the discovery and only got formal recognition later in life for example in 1966 being accreditted the Enrico Fermi Award, 30 years after her initial discovery.",
        lifespan:"1878-1968",
        link:"https://en.wikipedia.org/wiki/Lise_Meitner",
        img_src:"/playground_assets/lise_meitner_%5B1878-1968%5D%2C_lecturing_at_catholic_university%2C_washington%2C_d.c.%2C_1946-200w.jpg",
        img_alt:"Lise Meitner woman scientist in her labaratory portrait",
        icon_src:"/playground_assets/nuclear_fission-200h.png",
        icon_alt:" Nuclear fission explanatory model discovered by Lise Meitner",
        icon_credit: "Original:  Stefan-Xp (talk · contribs) / Vectorization:  Wondigoma (talk · contribs), CC BY-SA 3.0 <http://creativecommons.org/licenses/by-sa/3.0/>, via Wikimedia Commons",
    },
    {
        name:"Paulina Luisi",
        category:"politics",
        description:"Paulina Luisi is the first latin american woman to participate in teh League of Nations as a government representative. She is also the first Uruguayan woman to ever receive a medical degree. As part of the feminist movement she fought for women's right to vote and obligatory sex-health education in schools.",
        lifespan:"1875-1950",
        link:"https://en.wikipedia.org/wiki/Paulina_Luisi",
        img_src:"https://upload.wikimedia.org/wikipedia/commons/1/1d/Paulina_Luisi.jpg",
        img_alt:"Paulina Luisi",
        icon_src:"https://upload.wikimedia.org/wikipedia/commons/c/c5/Flag_of_the_League_of_Nations_%281939%29.svg",
        icon_alt:" Woman education league of nations ",
        icon_credit: "Martin Grandjean This W3C-unspecified vector image was created with Inkscape., CC BY-SA 4.0 <https://creativecommons.org/licenses/by-sa/4.0>, via Wikimedia Commons",
    },
    {
        name:"",
        category:"",
        description:"",
        lifespan:"",
        link:"",
        img_src:"",
        img_alt:"",
        icon_src:"",
        icon_alt:"",
    },
    {
        name:"",
        category:"",
        description:"",
        lifespan:"",
        link:"",
        img_src:"",
        img_alt:"",
        icon_src:"",
        icon_alt:"",
    },
    
]